-- CreateTable
CREATE TABLE "LuxuryDestination" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "propertyName" TEXT NOT NULL,
    "propertyType" TEXT NOT NULL,
    "starRating" TEXT,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "postalCode" TEXT,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "website" TEXT,
    "checkInTime" TEXT,
    "checkOutTime" TEXT,
    "languagesSpoken" TEXT[],
    "description" TEXT NOT NULL,
    "highlights" TEXT,
    "amenities" TEXT[],
    "roomTypes" TEXT,
    "totalRooms" INTEGER,
    "yearBuilt" INTEGER,
    "lastRenovated" INTEGER,
    "awards" TEXT,
    "sustainabilityPractices" TEXT[],
    "wheelchairAccessible" BOOLEAN NOT NULL DEFAULT false,
    "accessibleRooms" INTEGER,
    "accessibleBathrooms" BOOLEAN NOT NULL DEFAULT false,
    "accessibleParking" BOOLEAN NOT NULL DEFAULT false,
    "accessibleRestaurants" BOOLEAN NOT NULL DEFAULT false,
    "accessiblePools" BOOLEAN NOT NULL DEFAULT false,
    "brailleSignage" BOOLEAN NOT NULL DEFAULT false,
    "hearingImpairedServices" BOOLEAN NOT NULL DEFAULT false,
    "visualImpairedServices" BOOLEAN NOT NULL DEFAULT false,
    "serviceAnimalsAllowed" BOOLEAN NOT NULL DEFAULT false,
    "cancellationPolicy" TEXT NOT NULL,
    "petPolicy" TEXT,
    "smokingPolicy" TEXT,
    "childrenPolicy" TEXT,
    "groupPolicy" TEXT,
    "depositRequired" BOOLEAN NOT NULL DEFAULT false,
    "depositAmount" TEXT,
    "minimumStay" TEXT,
    "ageRestriction" TEXT,
    "quietHours" TEXT,
    "specialOffers" TEXT,
    "loyaltyProgram" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "LuxuryDestination_pkey" PRIMARY KEY ("id")
);
