-- CreateTable
CREATE TABLE "JetForCharter" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "jetName" TEXT NOT NULL,
    "aircraftType" TEXT NOT NULL,
    "manufacturer" TEXT NOT NULL,
    "yearOfManufacture" TEXT NOT NULL,
    "registrationNumber" TEXT NOT NULL,
    "seatingCapacity" TEXT NOT NULL,
    "cabinConfiguration" TEXT NOT NULL,
    "maximumRange" TEXT NOT NULL,
    "cruisingSpeed" TEXT NOT NULL,
    "baggageCapacity" TEXT NOT NULL,
    "homeBase" TEXT NOT NULL,
    "availableRoutes" TEXT NOT NULL,
    "operatingDays" TEXT NOT NULL,
    "noticeRequired" TEXT NOT NULL,
    "pricePerHour" TEXT NOT NULL,
    "minimumFlightTime" TEXT NOT NULL,
    "tripOption" TEXT NOT NULL,
    "additionalFees" TEXT NOT NULL,
    "discounts" TEXT,
    "cabinFeatures" JSONB NOT NULL,
    "inFlightMeals" BOOLEAN NOT NULL DEFAULT false,
    "flightAttendant" BOOLEAN NOT NULL DEFAULT false,
    "petsAllowed" BOOLEAN NOT NULL DEFAULT false,
    "smokingAllowed" BOOLEAN NOT NULL DEFAULT false,
    "exteriorImages" JSONB,
    "interiorImages" JSONB,
    "videoLink" TEXT,
    "luxuryCarService" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "JetForCharter_pkey" PRIMARY KEY ("id")
);
